- name: setup rabbitmq server
  hosts: rabbitmq
  become: yes


  tasks:
    - name: install rabbitmq
      ansible.builtin.package:
        name: redis
        state: present

    - name: start and enable mysql service
      ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started