- name: setup redis server
  hosts: mongodb
  become: yes


  tasks:
  - name: enable redis 7
    ansible.builtin.command: dnf module enable redis:7 -y  

  - name: install redis
    ansible.builtin.package:
    name: redis
    state: present


